Run the redis test server with enable-debug-command
This is required for Redis >= 7.x, cf.
https://raw.githubusercontent.com/redis/redis/7.0/00-RELEASENOTES:

    * MODULE and DEBUG commands disabled (protected) by default, for
      better security (#9920)

Without this patch, some unit tests fail:

```
=== RUN   TestLatency
    reply_test.go:256:
                Error Trace:    /<<PKGBUILDDIR>>/_build/src/github.com/gomodule/redigo/redis/reply_test.go:256
                Error:          Received unexpected error:
                                ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
                Test:           TestLatency
--- FAIL: TestLatency (0.00s)
=== RUN   TestLatencyHistories
    reply_test.go:304:
                Error Trace:    /<<PKGBUILDDIR>>/_build/src/github.com/gomodule/redigo/redis/reply_test.go:304
                Error:          Received unexpected error:
                                ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
                Test:           TestLatencyHistories
--- FAIL: TestLatencyHistories (0.00s)
```